- name: Download and Setup required tools for PetClinic App
  hosts: part2
  tasks:
    - name: Download Tomcat 10
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.11/bin/apache-tomcat-10.1.11.tar.gz
        dest: /home/pet-clinic
    
    - name: untar tomcat 10
      unarchive: 
        src: /home/pet-clinic/apache-tomcat-10.1.11.tar.gz
        dest: /home/pet-clinic
        remote_src: yes
    
    - name: start tomcat server
      script: /home/pet-clinic/apache-tomcat-10.1.11/bin/startup.sh

    - name: download jenkins
      get_url:
        url: https://get.jenkins.io/war-stable/2.401.2/jenkins.war
        dest: /home/pet-clinic
    
    - name: startup jenkins
      command: java -jar jenkins.war --httpPort=9000
